### ISSUE TITLE
메인 페이지 이슈

### ISSUE THREAD

**Issue by daeni-dang** [boostcampaitech4lv23recsys2/final-project-level3-recsys-12#76]
:speech_balloon: Issue
---
메인 페이지에서 좋아요를 누른 후 새로운 추천 받기를 눌렀을 때 좋아요를 누르지 않은 상품임에도 좋아요가 눌린 채로 새로고침 되는 현상 발생
- 새로운 추천 결과에서만 발생
```python
{#each new_item_list as item}
<div class="col mb-3">
  <Like item_id={item.item_id} />
  <a use:link href="/detail/{item.item_id}" class="link-detail">
```
- 상단의 코드에서 `<Like ... >` 부분이 실행되지 않는 것으로 추정. (Like 컴포넌트 내부에서 해당 아이템이 prefer 테이블에 존재하는지 확인)

To reproduce
---
1. [새로운 추천 받기] 클릭
2. 추천된 아이템에 좋아요 클릭
3. [새로운 추천 받기] 클릭

:heavy_check_mark: To do
---
- [ ] 완료된 일
- [x] 해야할 일

해결 방법
---
[참고 링크](https://heropy.blog/2019/09/29/svelte/) -> "키 블록" 검색
문제 원인 : 컴포넌트는 최초 페이지 로딩 시에만 실행이 되는 문제가 있었다. 이를 해결하기 위해 데이터 변경이 이루어지면 블록 안의 내용을 다시 렌더링해주어야 한다.

**Comment by 7dudtj** [comment]
수고하셨습니다!
